### ISSUE TITLE
Update xero connector for the new APIs

### ISSUE THREAD

**Issue by mpmunasinghe** [wso2-extensions/esb-connector-xero#5]
**Description:**
Current xero endpoint used within xero conector is scheduled to deprecate on March 31 2019. Hence we need to update the connector to the new rest API. 

 https://developer.xero.com/documentation/payroll-api-us/employees

https://developer.xero.com/documentation/api/employees

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anupama-pathirage** [comment]
Moved to https://github.com/wso2/micro-integrator/issues/3529
